---
- name: add ansible repo
  apt: deb='https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb'
- name: install elixir
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - esl-erlang
    - elixir
