---
- name: update package sources
  apt: update_cache=yes cache_valid_time=3600
- name: install nginx packages
  apt: name={{ item }} state=present
  with_items:
    - nginx

- name: create ssl certificate directory
  file: path=/etc/nginx/ssl state=directory
- name: create self signed certificate
  command: openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -subj "/C=US/ST=Missouri/L=Kansas City/O=IT/CN={{ hostname }}" -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
  args:
    creates: /etc/nginx/ssl/nginx.crt
  notify:
    - restart nginx
