---
- name: update package sources
  apt: update_cache=yes cache_valid_time=3600
- name: install mysql packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
- name: install mysql bindings for python
  apt: name=python-mysqldb state=present
- name: update mysql bind address
#  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="^bind-address" line="bind-address = {{ansible_default_ipv4.address}}"
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="^bind-address" line="bind-address = 0.0.0.0"
  notify:
    - restart mysql
- name: secure mysql
  mysql_db: name=test state=absent
- name: add mysql web user
  mysql_user: name=web password=web host=% priv=*.*:ALL
