---
- name: update package sources
  apt: update_cache=yes cache_valid_time=3600
- name: install drush/drupal related packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-client

- name: install drush
  get_url: url=http://files.drush.org/drush.phar dest=/usr/local/bin/drush
- name: insure drush is executable  
  file: path=/usr/local/bin/drush mode=0755
- name: install drupal console
  get_url: url=https://drupalconsole.com/installer dest=/usr/local/bin/drupal
- name: insure drush is executable  
  file: path=/usr/local/bin/drupal mode=0755

- name: check for acquia files
  become: false
  local_action: stat path=.acquia
  register: acquia_files
  ignore_errors: True
- name: copy acquia files
  copy: src=.acquia dest=/home/vagrant owner=vagrant
  become: yes
  become_user: vagrant
  when: acquia_files.stat.exists
- name: check for drush files
  become: false
  local_action: stat path=.drush
  register: drush_files
  ignore_errors: True
- name: copy drush files
  copy: src=.drush/ dest=/home/vagrant/.drush owner=vagrant
  become: yes
  become_user: vagrant
  when: drush_files.stat.exists
- name: create drush dump dir
  file: path=/home/vagrant/drush-dump-dir state=directory
  become: yes
  become_user: vagrant
- name: check for drupal console files
  stat: path=/home/vagrant/.console
  register: drupal_console_files
- name: initialize drupal config
  command: drupal init --override --yes
  become: yes
  become_user: vagrant
  when: drupal_console_files.stat.exists == False

- name: configure drupal sites 
  template: src=drupal.nginx.j2 dest=/etc/nginx/sites-available/{{ item.key }}
  with_dict: "{{ drupal_sites }}"
- name: enable drupal sites
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  with_dict: "{{ drupal_sites }}"
  notify:
    - restart nginx
